# Generated by Django 3.1.7 on 2021-07-24 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TblIncome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_income', models.IntegerField(blank=True, null=True)),
                ('income_category', models.CharField(blank=True, max_length=20, null=True)),
                ('income_name', models.CharField(max_length=50, null=True)),
                ('income_value', models.IntegerField(blank=True, null=True)),
                ('income_dt', models.DateField(blank=True, null=True)),
                ('updated_dt', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbl_income',
                'managed': False,
            },
        ),
    ]
